name: invo_mobile
description: A Invo POS for Mobile Devices.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.77+92

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  device_info: ^2.0.3
  meta: ^1.1.6
  http: ^0.13.4
  shared_preferences: ^2.0.13
  showcaseview: ^1.1.5
  json_annotation: ^4.4.0
  socket_io_client: ^1.0.2
  uuid: ^3.0.6
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.4.1
  oktoast: ^3.1.5
  json_serializable: ^6.1.5
  blue_thermal_printer: ^1.2.0
  path_provider: ^2.0.9
  # flutter_barcode_scanner: ^0.1.7
  charts_flutter: ^0.12.0
  sqflite: ^2.0.2
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.4+11
  flutter_image_compress: ^1.1.0
  pdf: ^3.7.2
  printing: ^5.7.3
  # get_ip: ^0.4.0
  esc_pos_printer: ^4.1.0
  charset_converter: ^2.1.0
  characters: ^1.0.0
  flutter_secure_storage: ^8.0.0
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  esc_pos_utils: any
  file_picker: ^4.5.1
  url_launcher: ^6.0.20
  web_socket_channel: ^2.1.0
  flutter_sound: ^9.1.7
  csv: ^5.0.1
  permission_handler: ^10.2.0
  # flutter_tts: ^3.3.3
  # flutter_text_to_speech: ^3.0.7

  dio: ^4.0.4
  image: ^3.1.3
  sliding_up_panel: ^2.0.0+1
  platform_device_id: ^1.0.1
  package_info_plus: ^1.4.0
  cryptography: ^2.0.5
  crypto: ^3.0.1
  encrypt: ^5.0.1
  # ext_storage: ^1.0.3
  # flutter_usb_printer: ^0.1.0+1
  android_path_provider: ^0.3.0
  # downloads_path_provider: ^0.1.0
  # downloads_path_provider_28: ^0.1.2
  esc_pos_utils_plus: ^2.0.1+6
  lan_scanner: ^3.5.0
  network_info_plus: ^3.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #flutter_android_plugin:
  #  path: ../flutter_android_plugin

  android_plugin:
    path: ../android_plugin
  

dependency_overrides:
  image_picker_android: 0.8.4+13
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    #icons ( Home )
    - assets/
    - assets/sound/service_bell_daniel_simion.mp3
    - assets/icons/
    - assets/i18n/
    - assets/fonts/
      #tables icons
    - assets/Tables/1_Person/
    - assets/Tables/2_Persons/
    - assets/Tables/4_Persons/
    - assets/Tables/6_Persons/
    - assets/Tables/8_Persons/
    - assets/Tables/10_Persons/
    - assets/saudi.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  
